CREATE TABLE [edw].[FT_Beregning_BU_140702_1_Arkiv] (
    [01_Beregning]        VARCHAR (20)     NULL,
    [01a_BeregnDato]      VARCHAR (10)     NULL,
    [01b_PrincipDato]     VARCHAR (10)     NULL,
    [02_Beregningstekst]  VARCHAR (100)    NULL,
    [03_BeregningNr]      VARCHAR (20)     NULL,
    [04_Fb]               VARCHAR (10)     NULL,
    [05_Mat]              VARCHAR (18)     NULL,
    [06_MaterialeTekst]   VARCHAR (50)     NULL,
    [07_LitraGr]          VARCHAR (15)     NULL,
    [08_StatGr]           VARCHAR (20)     NULL,
    [09_Mart]             VARCHAR (10)     NULL,
    [10_Sm]               VARCHAR (1)      NULL,
    [11_Beh]              DECIMAL (18, 3)  NULL,
    [12_GlGPris]          DECIMAL (18, 3)  NULL,
    [13_Vaerdi_GP]        DECIMAL (18, 3)  NULL,
    [14_LNType]           VARCHAR (4)      NOT NULL,
    [15_LavNedPct]        DECIMAL (38, 15) NULL,
    [16_LogNedBrutto]     DECIMAL (38, 6)  NULL,
    [17_NedskrNetto]      DECIMAL (38, 6)  NULL,
    [18_NedKorrNytMat]    DECIMAL (38, 6)  NULL,
    [19_FTrMd]            VARCHAR (7)      NULL,
    [20_NedKorrIndk]      DECIMAL (38, 6)  NULL,
    [21_IndkLagerBeh]     DECIMAL (38, 3)  NULL,
    [22_IndkLagerVaerdi]  DECIMAL (38, 3)  NULL,
    [23_Vaerdi_SP]        DECIMAL (18, 3)  NULL,
    [24_Forskel]          DECIMAL (19, 3)  NULL,
    [25_LitrNedPct]       DECIMAL (5, 2)   NULL,
    [26_LitraNedVaerdi]   DECIMAL (24, 5)  NULL,
    [27_DUF]              INT              NULL,
    [28_LangNedPct]       DECIMAL (13, 7)  NULL,
    [29_LangNedVaerdi]    DECIMAL (32, 10) NULL,
    [30_RID]              DECIMAL (38, 6)  NULL,
    [31_RaekNedPct]       DECIMAL (38, 15) NULL,
    [32_RaekkeNedVaerdi]  DECIMAL (38, 6)  NULL,
    [33_StatNedPct]       DECIMAL (8, 7)   NULL,
    [34_StatNedVaerdi]    DECIMAL (27, 10) NULL,
    [35_StatNedReelt]     DECIMAL (38, 6)  NULL,
    [36_RestAabnBalBeh]   DECIMAL (38, 3)  NULL,
    [37_AabnNedPct]       NUMERIC (2, 2)   NULL,
    [38_AabnBalNedVaerdi] NUMERIC (38, 6)  NULL,
    [DI_Materiale]        INT              NULL,
    [DI_Tid]              VARCHAR (10)     NULL
);

